# Generated by Django 4.0.5 on 2022-06-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'ドメイン',
                'verbose_name_plural': 'ドメイン',
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名前')),
            ],
            options={
                'verbose_name': '科',
                'verbose_name_plural': '科',
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名前')),
            ],
            options={
                'verbose_name': '界',
                'verbose_name_plural': '界',
                'db_table': 'kingdom',
            },
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ja', models.CharField(max_length=32, verbose_name='名前')),
                ('name_en', models.CharField(max_length=64, verbose_name='Name')),
                ('status', models.PositiveIntegerField(choices=[(0, '生存'), (1, '絶滅')], default=0, verbose_name='生存ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='organism.domain', verbose_name='ドメイン')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='organism.family', verbose_name='科')),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='organism.kingdom')),
            ],
            options={
                'verbose_name': '生物',
                'verbose_name_plural': '生物',
                'db_table': 'organism',
            },
        ),
    ]
