# Generated by Django 4.0.5 on 2022-07-05 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='organism.kingdom', verbose_name='界'),
        ),
    ]
