# Generated by Django 4.0.5 on 2022-07-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0003_alter_organism_kingdom'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='outline',
            field=models.TextField(blank=True, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='domain',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='organism.domain', verbose_name='ドメイン'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='family',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='organism.family', verbose_name='科'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='kingdom',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='organism.kingdom', verbose_name='界'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='name_en',
            field=models.CharField(blank=True, max_length=64, verbose_name='Name'),
        ),
    ]
