# Generated by Django 4.0.5 on 2022-07-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0004_organism_outline_alter_organism_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='organism.domain', verbose_name='ドメイン'),
        ),
        migrations.AlterField(
            model_name='organism',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '生存'), (1, '絶滅')], default=0, verbose_name='生存ステータス'),
        ),
    ]
