# Generated by Django 4.0.5 on 2022-07-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0006_alter_organism_family_alter_organism_kingdom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='name_en',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
    ]
