# Generated by Django 4.0.5 on 2022-07-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0007_alter_organism_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='画像'),
        ),
    ]
