# Generated by Django 4.0.5 on 2022-07-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0008_organism_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像'),
        ),
    ]
