# Generated by Django 4.0.5 on 2022-07-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0009_alter_organism_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名前')),
            ],
            options={
                'verbose_name': '綱',
                'verbose_name_plural': '綱',
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名前')),
            ],
            options={
                'verbose_name': '門',
                'verbose_name_plural': '門',
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名前')),
            ],
            options={
                'verbose_name': '目',
                'verbose_name_plural': '目',
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='organism',
            name='classis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='organism.classis', verbose_name='綱'),
        ),
        migrations.AddField(
            model_name='organism',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='organism.division', verbose_name='門'),
        ),
        migrations.AddField(
            model_name='organism',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism', to='organism.order', verbose_name='目'),
        ),
    ]
