# Generated by Django 4.0.5 on 2022-07-05 06:02

from django.db import migrations, models
import organism.models


class Migration(migrations.Migration):

    dependencies = [
        ('organism', '0010_classis_division_order_organism_classis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=organism.models._organism_pic_upload_to, verbose_name='画像'),
        ),
    ]
