# Generated by Django 4.0.3 on 2022-07-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='トッピング名')),
                ('price', models.IntegerField(verbose_name='値段')),
                ('outline', models.TextField(verbose_name='説明')),
            ],
            options={
                'verbose_name': 'トッピング',
                'verbose_name_plural': 'トッピング',
                'db_table': 'topping',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ピザ名')),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), (
                    'L', 'Large')], default=('M', 'Medium'), max_length=50, verbose_name='サイズ')),
                ('toppings', models.ManyToManyField(
                    to='pizza.topping', verbose_name='トッピング')),
            ],
            options={
                'verbose_name': 'ピザ',
                'verbose_name_plural': 'ピザ',
                'db_table': 'pizza',
            },
        ),
    ]
