# Generated by Django 4.0.3 on 2022-07-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(default=1, verbose_name='値段'),
            preserve_default=False,
        ),
    ]
